baseURL = 'https://nixdork.org/'
languageCode = 'en-us'
title = 'NixDork Labs'
theme = 'cactus'
copyright = 'nixdork.org'

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "SourceHut"
url = "https://sr.ht/~gorauskas/"
weight = 4

[[menu.main]]
name = "GitHub"
url = "https://github.com/nixdork"
weight = 5


[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  logo = "img/glider.png"
  favicon = "img/favicon.ico"

  # Home page settings
  description = """NixDork Labs is a collection of experiments, hacks, and musings on coding by Jonas Gorauskas.
  
_Vīta brevis, ars longa, occāsiō praeceps, experīmentum perīculōsum, iūdicium difficile._
  """
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gorauskas" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
